import { Permission } from '@shared/models/permission.model';

export const transactionsPermissionsTree: Permission[] = [
  {
    id: 'Request',
    name: 'الصادر والوارد',
    nameAr: 'الصادر والوارد',
    nameEn: 'Requests',
    checked: true,
    pages: [
      {
        id: 'ViewRequest',
        name: ' عرض الصادر والوارد',
        nameAr: ' عرض الصادر والوارد',
        nameEn: 'View requests',
        checked: false,
      },
      {
        id: 'CreateRequest',
        name: 'إنشاء صادر و وارد',
        nameAr: 'إنشاء صادر و وارد',
        nameEn: 'Create request',
        checked: false,
      },
      {
        id: 'UpdateRequest',
        name: 'تعديل صادر و وارد',
        nameAr: 'تعديل صادر و وارد',
        nameEn: 'Update request',
        checked: false,
      },
      {
        id: 'DeleteRequest',
        name: 'حذف صادر و وارد',
        nameAr: 'حذف صادر و وارد',
        nameEn: 'Delete request',
        checked: false,
      },
      {
        id: 'ResetRequestWorkflowSteps',
        name: 'اعادة ضبط دورة العمل',
        nameAr: 'اعادة ضبط دورة العمل',
        nameEn: 'Reset request workflow steps',
        checked: false,
      },
      {
        id: 'ExportRequestsToExcel',
        name: 'تصدير',
        nameAr: 'تصدير',
        nameEn: 'Export to excel',
        checked: false,
      },
    ],
  },
  {
    id: 'DocumentType',
    name: 'قائمة الوثائق',
    nameAr: 'قائمة الوثائق',
    nameEn: 'Document types',
    checked: true,
    pages: [
      {
        id: 'ViewDocumentType',
        name: 'عرض قائمة الوثائق',
        nameAr: 'عرض قائمة الوثائق',
        nameEn: 'View document types',
        checked: false,
      },
      {
        id: 'CreateDocumentType',
        name: 'إنشاء نوع وثيقة',
        nameAr: 'إنشاء نوع وثيقة',
        nameEn: 'Create document type',
        checked: false,
      },
      {
        id: 'UpdateDocumentType',
        name: 'تعديل نوع وثيقة',
        nameAr: 'تعديل نوع وثيقة',
        nameEn: 'Update document type',
        checked: false,
      },
      {
        id: 'DeleteDocumentType',
        name: 'حذف نوع وثيقة',
        nameAr: 'حذف نوع وثيقة',
        nameEn: 'Delete document type',
        checked: false,
      },
    ],
  },
  {
    id: 'RequestType',
    name: 'أنواع الوثائق',
    nameAr: 'أنواع الوثائق',
    nameEn: 'Request types',
    checked: true,
    pages: [
      {
        id: 'ViewRequestType',
        name: 'عرض أنواع الوثائق',
        nameAr: 'عرض أنواع الوثائق',
        nameEn: 'View request types',
        checked: false,
      },
      {
        id: 'CreateRequestType',
        name: 'إنشاء نوع وثيقة',
        nameAr: 'إنشاء نوع وثيقة',
        nameEn: 'Create request type',
        checked: false,
      },
      {
        id: 'UpdateRequestType',
        name: 'تعديل نوع وثيقة',
        nameAr: 'تعديل نوع وثيقة',
        nameEn: 'Update request type',
        checked: false,
      },
      {
        id: 'DeleteRequestType',
        name: 'حذف نوع وثيقة',
        nameAr: 'حذف نوع وثيقة',
        nameEn: 'Delete request type',
        checked: false,
      },
    ],
  },
  {
    id: 'Classification',
    name: 'درجات السرية',
    nameAr: 'درجات السرية',
    nameEn: 'Classifications',
    checked: true,
    pages: [
      {
        id: 'ViewClassifications',
        name: 'عرض درجات السرية',
        nameAr: 'عرض درجات السرية',
        nameEn: 'View classifications',
        checked: false,
      },
      {
        id: 'CreateClassification',
        name: 'إنشاء درجة سرية',
        nameAr: 'إنشاء درجة سرية',
        nameEn: 'Create classification',
        checked: false,
      },
      {
        id: 'UpdateClassification',
        name: 'تعديل درجة سرية',
        nameAr: 'تعديل درجة سرية',
        nameEn: 'Update classification',
        checked: false,
      },
      {
        id: 'DeleteClassification',
        name: ' حذف درجة سرية',
        nameAr: ' حذف درجة سرية',
        nameEn: 'Delete classification',
        checked: false,
      },
    ],
  },
  {
    id: 'RequestContainer',
    name: 'المعاملات',
    nameAr: 'المعاملات',
    nameEn: 'Request containers',
    checked: true,
    pages: [
      {
        id: 'ViewRequestContainer',
        name: 'عرض المعاملات',
        nameAr: 'عرض المعاملات',
        nameEn: 'View request containers',
        checked: false,
      },
      {
        id: 'CreateRequestContainer',
        name: 'إنشاء معاملة',
        nameAr: 'إنشاء معاملة',
        nameEn: 'Create request container',
        checked: false,
      },
      {
        id: 'UpdateRequestContainer',
        name: 'تعديل معاملة',
        nameAr: 'تعديل معاملة',
        nameEn: 'Update request container',
        checked: false,
      },
      {
        id: 'DeleteRequestContainer',
        name: 'حذف معاملة',
        nameAr: 'حذف معاملة',
        nameEn: 'Delete request container',
        checked: false,
      },
      {
        id: 'ModifyProcessType',
        name: 'تعديل الية المعالجة',
        nameAr: 'تعديل الية المعالجة',
        nameEn: 'Modify process type',
        checked: false,
      },
      {
        id: 'UpdateRequestContainerAccessibility',
        name: 'تحديد المستخدمين للاطلاع علي المعاملة',
        nameAr: 'تحديد المستخدمين للاطلاع علي المعاملة',
        nameEn: 'Identify users who can access transaction',
        checked: false,
      },
      {
        id: 'CommitteePhoneApprovals',
        name: 'تعديل موافقة الاعضاء',
        nameAr: 'تعديل موافقة الاعضاء',
        nameEn: "Edit Members' Approval",
        checked: false,
      },
    ],
  },
  {
    id: 'PendingRequests',
    name: 'قيد الانتظار',
    nameAr: 'قيد الانتظار',
    nameEn: 'Pending Requests',
    checked: true,
    pages: [
      {
        id: 'ViewPendingRequests',
        name: 'عرض قيد الانتظار',
        nameAr: 'عرض قيد الانتظار',
        nameEn: 'View pending requests',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
    ],
  },
  {
    id: 'Action',
    name: 'الاجراءات',
    nameAr: 'الاجراءات',
    nameEn: 'Actions',
    checked: true,
    pages: [
      {
        id: 'ViewAction',
        name: 'عرض الاجراءات',
        nameAr: 'عرض الاجراءات',
        nameEn: 'View actions',
        checked: false,
      },
      {
        id: 'CreateAction',
        name: 'إنشاء اجراء',
        nameAr: 'إنشاء اجراء',
        nameEn: 'Create action',
        checked: false,
      },
      {
        id: 'UpdateAction',
        name: 'تعديل اجراء',
        nameAr: 'تعديل اجراء',
        nameEn: 'Update action',
        checked: false,
      },
      {
        id: 'DeleteAction',
        name: 'حذف اجراء',
        nameAr: 'حذف اجراء',
        nameEn: 'Delete action',
        checked: false,
      },
    ],
  },
  {
    id: 'StepCategory',
    name: 'تصنيف الخطوات',
    nameAr: 'تصنيف الخطوات',
    nameEn: 'Step categories',
    checked: true,
    pages: [
      {
        id: 'ViewStepCategory',
        name: 'عرض تصنيف الخطوات',
        nameAr: 'عرض تصنيف الخطوات',
        nameEn: 'View step categories',
        checked: false,
      },
      {
        id: 'CreateStepCategory',
        name: 'إنشاء تصنيف خطوة',
        nameAr: 'إنشاء تصنيف خطوة',
        nameEn: 'Create step category',
        checked: false,
      },
      {
        id: 'UpdateStepCategory',
        name: 'تعديل تصنيف خطوة',
        nameAr: 'تعديل تصنيف خطوة',
        nameEn: 'Update step category',
        checked: false,
      },
      {
        id: 'DeleteStepCategory',
        name: 'حذف تصنيف خطوة',
        nameAr: 'حذف تصنيف خطوة',
        nameEn: 'Delete step category',
        checked: false,
      },
    ],
  },
  {
    id: 'Step',
    name: 'الخطوات',
    nameAr: 'الخطوات',
    nameEn: 'Steps',
    checked: true,
    pages: [
      {
        id: 'ViewStep',
        name: 'عرض الخطوات',
        nameAr: 'عرض الخطوات',
        nameEn: 'View steps',
        checked: false,
      },
      {
        id: 'CreateStep',
        name: 'إنشاء خطوة',
        nameAr: 'إنشاء خطوة',
        nameEn: 'Create step',
        checked: false,
      },
      {
        id: 'UpdateStep',
        name: 'تعديل خطوة',
        nameAr: 'تعديل خطوة',
        nameEn: 'Update step',
        checked: false,
      },
      {
        id: 'DeleteStep',
        name: 'حذف خطوة',
        nameAr: 'حذف خطوة',
        nameEn: 'Delete step',
        checked: false,
      },
    ],
  },
  {
    id: 'Actor',
    name: 'المتفاعلون',
    nameAr: 'المتفاعلون',
    nameEn: 'Actors',
    checked: true,
    pages: [
      {
        id: 'ViewActor',
        name: 'عرض المتفاعلون',
        nameAr: 'عرض المتفاعلون',
        nameEn: 'View actors',
        checked: false,
      },
      {
        id: 'CreateActor',
        name: 'إنشاء متفاعل',
        nameAr: 'إنشاء متفاعل',
        nameEn: 'Create actor',
        checked: false,
      },
      {
        id: 'UpdateActor',
        name: 'تعديل متفاعل',
        nameAr: 'تعديل متفاعل',
        nameEn: 'Update actor',
        checked: false,
      },
      {
        id: 'DeleteActor',
        name: 'حذف متفاعل',
        nameAr: 'حذف متفاعل',
        nameEn: 'Delete actor',
        checked: false,
      },
    ],
  },
  {
    id: 'Schema',
    name: 'دورات حياة المعاملة',
    nameAr: 'دورات حياة المعاملة',
    nameEn: 'Workflows',
    checked: true,
    pages: [
      {
        id: 'ViewSchema',
        name: 'عرض دورات حياة المعاملة',
        nameAr: 'عرض دورات حياة المعاملة',
        nameEn: 'View workflows',
        checked: false,
      },
      {
        id: 'CreateSchema',
        name: 'إنشاء دورة حياة المعاملة',
        nameAr: 'إنشاء دورة حياة المعاملة',
        nameEn: 'Create workflow',
        checked: false,
      },
      {
        id: 'UpdateSchema',
        name: 'تعديل دورة حياة المعاملة',
        nameAr: 'تعديل دورة حياة المعاملة',
        nameEn: 'Update workflow',
        checked: false,
      },
      {
        id: 'DeleteSchema',
        name: 'حذف دورة حياة المعاملة',
        nameAr: 'حذف دورة حياة المعاملة',
        nameEn: 'Delete workflow',
        checked: false,
      },
    ],
  },
  {
    id: 'Inquiry',
    name: 'استفسار',
    nameAr: 'استفسار',
    nameEn: 'Inquiry',
    checked: true,
    pages: [
      {
        id: 'ViewInquiry',
        name: 'عرض الاستفسارات',
        nameAr: 'عرض الاستفسارات',
        nameEn: 'View inquiries',
        checked: false,
      },
      {
        id: 'CreateInquiry',
        name: 'إنشاء استفسار',
        nameAr: 'إنشاء استفسار',
        nameEn: 'Create inquiry',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },

      {
        id: 'ReplyInquiry',
        name: 'الرد علي الاستفسار',
        nameAr: 'الرد علي الاستفسار',
        nameEn: 'Reply inquiry',
        checked: false,
      },

      {
        id: 'ReplyApprovalInquiry',
        name: 'اعتماد الرد علي الاستفسار',
        nameAr: 'اعتماد الرد علي الاستفسار',
        nameEn: 'Reply Approval',
        checked: false,
      },
    ],
  },
  {
    id: 'UserDelegations',
    name: 'التفويضات',
    nameAr: 'التفويضات',
    nameEn: 'UserDelegations',
    checked: true,
    pages: [
      {
        id: 'UserDelegate',
        name: 'الاطلاع علي التفويضات',
        nameAr: 'الاطلاع علي التفويضات',
        nameEn: 'View delegations',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },

      {
        id: 'ViewUsersDelegations',
        name: 'الاطلاع علي تفويضات المستخدم',
        nameAr: ' ViewUsersDelegations',
        nameEn: 'View users elegations',
        checked: false,
      },
      {
        id: 'AdministrateDelegations',
        name: 'ادارة تفويضات المستخدم',
        nameAr: 'ادارة تفويضات المستخدم',
        nameEn: 'Administrate user delegations',
        checked: false,
      },
    ],
  },
  {
    id: 'Meeting',
    name: 'ادارة الاجتماعات',
    nameAr: 'ادارة الاجتماعات',
    nameEn: 'Meetings',
    checked: true,
    pages: [
      {
        id: 'ViewMeeting',
        name: 'عرض ادارة الاجتماعات',
        nameAr: 'عرض ادارة الاجتماعات',
        nameEn: 'View meetings',
        checked: false,
      },
      {
        id: 'CreateMeeting',
        name: 'إنشاء اجتماع',
        nameAr: 'إنشاء اجتماع',
        nameEn: 'Create meeting',
        checked: false,
      },
      {
        id: 'UpdateMeeting',
        name: 'تعديل اجتماع',
        nameAr: 'تعديل اجتماع',
        nameEn: 'Update meeting',
        checked: false,
      },
      {
        id: 'DeleteMeeting',
        name: 'حذف اجتماع',
        nameAr: 'حذف اجتماع',
        nameEn: 'Delete meeting',
        checked: false,
      },

      {
        id: 'ConfirmMeetingAttendance',
        name: 'تأكيد حضور الاجتماع',
        nameAr: 'تأكيد حضور الاجتماع',
        nameEn: 'Confirm meeting attendance',
        checked: false,
      },

      {
        id: 'MeetingAddUnScheduledRequests',
        name: 'اختيار المعاملات غير المجدولة',
        nameAr: 'اختيار المعاملات غير المجدولة',
        nameEn: 'Choose unscheduled requests',
        checked: false,
      },
    ],
  },
  {
    id: 'WorkflowDesigns',
    name: 'دورة العمل',
    nameAr: 'دورة العمل',
    nameEn: 'Work flows',
    checked: true,
    pages: [
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },

      {
        id: 'ModifyWorkflowDesigns',
        name: 'تعديل تصميم دورات العمل',
        nameAr: 'تعديل تصميم دورات العمل',
        nameEn: 'Modify work flow designs',
        checked: false,
      },
    ],
  },
  {
    id: 'Record',
    name: 'المحاضر',
    nameAr: 'المحاضر',
    nameEn: 'Records',
    checked: true,
    pages: [
      {
        id: 'ViewRecord',
        name: 'عرض المحاضر',
        nameAr: 'عرض المحاضر',
        nameEn: 'View records',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },

      {
        id: 'RemoveRecordMemberAction',
        name: 'حذف اجراءات المحضر',
        nameAr: 'حذف اجراءات المحضر',
        nameEn: 'Modify record actions',
        checked: false,
      },
      {
        id: 'RecordPhoneApprovalAction',
        name: 'ابداء الرأي هاتفيا',
        nameAr: 'ابداء الرأي هاتفيا',
        nameEn: 'Modify record actions',
        checked: false,
      },
      {
        id: 'ReplyRecordConservatism',
        name: 'الرد علي التحفظ',
        nameAr: 'الرد علي التحفظ',
        nameEn: 'Reply record conservatism',
        checked: false,
      },
      {
        id: 'UpdateRecordSignatureFormat',
        name: 'تعديل نماذج توقيعات المحضر',
        nameAr: 'تعديل نماذج توقيعات المحضر',
        nameEn: 'Update record signature format',
        checked: false,
      },
    ],
  },

  {
    id: 'Note',
    name: 'المذكرات',
    nameAr: 'المذكرات',
    nameEn: 'Notes',
    checked: true,
    pages: [
      {
        id: 'ViewNote',
        name: 'عرض المذكرات',
        nameAr: 'عرض المذكرات',
        nameEn: 'View notes',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
    ],
  },
  {
    id: 'RegularReport',
    name: 'التقارير',
    nameAr: 'التقارير',
    nameEn: 'Reports',
    checked: true,
    pages: [
      {
        id: 'ViewRegularReports',
        name: 'عرض التقارير',
        nameAr: 'عرض التقارير',
        nameEn: 'View reports',
        checked: false,
      },
      {
        id: 'CreateRegularReports',
        name: 'إنشاء تقرير',
        nameAr: 'إنشاء تقرير',
        nameEn: 'Create report',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },

      {
        id: 'SynchronizationRegularReports',
        name: 'مزامنة التقارير',
        nameAr: 'مزامنة التقارير',
        nameEn: 'Syncronize report',
        checked: false,
      },
      {
        id: 'ViewReportsLogs',
        name: 'عرض تاريخ التقارير',
        nameAr: 'عرض تاريخ التقارير',
        nameEn: 'View reports logs',
        checked: false,
      },
    ],
  },
  {
    id: 'DeliveryReceipt',
    name: 'بيانات التسليم',
    nameAr: 'بيانات التسليم',
    nameEn: 'Delivery Receipts',
    checked: true,
    pages: [
      {
        id: 'ViewDeliveryReceipt',
        name: 'عرض بيانات التسليم',
        nameAr: 'عرض بيانات التسليم',
        nameEn: 'View delivery receipts table',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },

      {
        id: 'UpdateDeliveryReceipt',
        name: 'تعديل تاريخ بيان التسليم',
        nameAr: 'تعديل تاريخ بيان التسليم',
        nameEn: 'Update delivery date',
        checked: false,
      },
      {
        id: 'CreateDeliveryReceipt',
        name: 'طباعة بيان التسليم',
        nameAr: 'طباعة بيان التسليم',
        nameEn: 'Print delivery receipt',
        checked: false,
      },
    ],
  },
];

export const systemPermissionsTree: Permission[] = [
  {
    id: 'RegulatoryDocuments',
    name: 'السياسات و اللوائح',
    nameAr: 'السياسات و اللوائح',
    nameEn: 'Regulatory Documents',
    checked: true,
    pages: [
      {
        id: 'ViewRegulatoryDocuments',
        name: ' عرض السياسات و اللوائح',
        nameAr: ' عرض السياسات و اللوائح',
        nameEn: 'View regulatory documents',
        checked: false,
      },
      {
        id: 'CreateRegulatoryDocuments',
        name: ' إنشاء السياسات و اللوائح',
        nameAr: ' إنشاء السياسات و اللوائح',
        nameEn: 'Create regulatory documents',
        checked: false,
      },
      {
        id: 'UpdateRegulatoryDocuments',
        name: ' تعديل السياسات و اللوائح',
        nameAr: ' تعديل السياسات و اللوائح',
        nameEn: 'Update regulatory documents',
        checked: false,
      },
      {
        id: 'DeleteRegulatoryDocuments',
        name: ' حذف السياسات و اللوائح',
        nameAr: ' حذف السياسات و اللوائح',
        nameEn: 'Delete regulatory documents',
        checked: false,
      },
    ],
  },
  {
    id: 'Foundation',
    name: 'الجهات',
    nameAr: 'الجهات',
    nameEn: 'Foundation',
    checked: true,
    pages: [
      {
        id: 'ViewFoundation',
        name: ' عرض الجهات',
        nameAr: ' عرض الجهات',
        nameEn: 'View foundations',
        checked: false,
      },
      {
        id: 'CreateFoundation',
        name: ' إنشاء جهة',
        nameAr: ' إنشاء جهة',
        nameEn: 'Create foundation',
        checked: false,
      },
      {
        id: 'UpdateFoundation',
        name: ' تعديل جهة',
        nameAr: ' تعديل جهة',
        nameEn: 'Update foundation',
        checked: false,
      },
      {
        id: 'DeleteFoundation',
        name: ' حذف جهة',
        nameAr: ' حذف جهة',
        nameEn: 'Delete foundation',
        checked: false,
      },
    ],
  },
  {
    id: 'Sector',
    name: 'القطاعات',
    nameAr: 'القطاعات',
    nameEn: 'Sectors',
    checked: true,
    pages: [
      {
        id: 'ViewSector',
        name: ' عرض القطاعات',
        nameAr: ' عرض القطاعات',
        nameEn: 'View sectors',
        checked: false,
      },
      {
        id: 'CreateSector',
        name: 'إنشاء قطاع',
        nameAr: 'إنشاء قطاع',
        nameEn: 'Create sector',
        checked: false,
      },
      {
        id: 'UpdateSector',
        name: ' تعديل قطاع',
        nameAr: ' تعديل قطاع',
        nameEn: 'Update sector',
        checked: false,
      },
      {
        id: 'DeleteSector',
        name: ' حذف قطاع',
        nameAr: ' حذف قطاع',
        nameEn: 'Delete sector',
        checked: false,
      },
    ],
  },
  {
    id: 'BenefitType',
    name: 'أنواع الطلبات',
    nameAr: 'أنواع الطلبات',
    nameEn: 'Benefit Types',
    checked: true,
    pages: [
      {
        id: 'ViewBenefitType',
        name: 'عرض أنواع الطلبات',
        nameAr: 'عرض أنواع الطلبات',
        nameEn: 'View benefit types',
        checked: false,
      },
      {
        id: 'CreateBenefitType',
        name: 'إنشاء نوع طلب',
        nameAr: 'إنشاء نوع طلب',
        nameEn: 'Create benefit type',
        checked: false,
      },
      {
        id: 'UpdateBenefitType',
        name: 'تعديل نوع الطلب',
        nameAr: 'تعديل نوع الطلب',
        nameEn: 'Update benefit type',
        checked: false,
      },
      {
        id: 'DeleteBenefitType',
        name: 'حذف نوع الطلب',
        nameAr: 'حذف نوع الطلب',
        nameEn: 'Delete benefit type',
        checked: false,
      },
    ],
  },

  {
    id: 'ReferralJustifications',
    name: 'مبررات احالة الموضوع',
    nameAr: 'مبررات احالة الموضوع',
    nameEn: 'ReferralJustifications',
    checked: true,
    pages: [
      {
        id: 'ViewReferralJustification',
        name: 'عرض مبررات احالة الموضوع',
        nameAr: 'عرض مبررات احالة الموضوع',
        nameEn: 'View ReferralJustifications',
        checked: false,
      },
      {
        id: 'CreateReferralJustification',
        name: 'إنشاء مبرر احالة موضوع',
        nameAr: 'إنشاء مبرر احالة موضوع',
        nameEn: 'Create Referral Justifications',
        checked: false,
      },
      {
        id: 'UpdateReferralJustification',
        name: 'تعديل مبرر احالة الموضوع',
        nameAr: 'تعديل مبرر احالة الموضوع',
        nameEn: 'Update Referral Justifications',
        checked: false,
      },
      {
        id: 'DeleteReferralJustification',
        name: 'حذف مبرر احالة الموضوع',
        nameAr: 'حذف مبرر احالة الموضوع',
        nameEn: 'Delete Referral Justifications',
        checked: false,
      },
    ],
  },
  {
    id: 'ProcessTypeJustifications',
    name: 'مبررات الية المعالجة',
    nameAr: 'مبررات الية المعالجة',
    nameEn: 'Process Type Justifications',
    checked: true,
    pages: [
      {
        id: 'ViewProcessTypeJustification',
        name: 'عرض مبررات الية المعالجة',
        nameAr: 'عرض مبررات الية المعالجة',
        nameEn: 'View Process Type Justifications',
        checked: false,
      },
      {
        id: 'CreateProcessTypeJustification',
        name: 'إنشاء مبرر الية المعالجة',
        nameAr: 'إنشاء مبرر الية المعالجة',
        nameEn: 'Create Process Type Justification',
        checked: false,
      },
      {
        id: 'UpdateProcessTypeJustification',
        name: 'تعديل مبرر الية المعالجة',
        nameAr: 'تعديل مبرر الية المعالجة',
        nameEn: 'Update Process Type Justification',
        checked: false,
      },
      {
        id: 'DeleteProcessTypeJustification',
        name: 'حذف مبرر الية المعالجة',
        nameAr: 'حذف مبرر الية المعالجة',
        nameEn: 'Delete Process Type Justification',
        checked: false,
      },
    ],
  },

  {
    id: 'Outcomes',
    name: 'نتائج التوصيات',
    nameAr: 'نتائج التوصيات',
    nameEn: 'Outcomes',
    checked: true,
    pages: [
      {
        id: 'ViewOutcome',
        name: 'عرض نتائج التوصيات',
        nameAr: 'عرض نتائج التوصيات',
        nameEn: 'View Outcomes',
        checked: false,
      },
      {
        id: 'CreateOutcome',
        name: 'إنشاء نتيجة توصية',
        nameAr: 'إنشاء نتيجة توصية',
        nameEn: 'Create Outcome',
        checked: false,
      },
      {
        id: 'UpdateOutcome',
        name: 'تعديل نتيجة توصية',
        nameAr: 'تعديل نتيجة توصية',
        nameEn: 'Update Outcome',
        checked: false,
      },
      {
        id: 'DeleteOutcome',
        name: 'حذف نتيجة توصية',
        nameAr: 'حذف نتيجة توصية',
        nameEn: 'Delete Outcome',
        checked: false,
      },
    ],
  },

  {
    id: 'RecommendationType',
    name: 'انواع التوصيات',
    nameAr: 'انواع التوصيات',
    nameEn: 'Recommendation Types',
    checked: true,
    pages: [
      {
        id: 'ViewRecommendationType',
        name: 'عرض انواع التوصيات',
        nameAr: 'عرض انواع التوصيات',
        nameEn: 'View Recommendation Types',
        checked: false,
      },
      {
        id: 'CreateRecommendationType',
        name: 'إنشاء نوع توصية',
        nameAr: 'إنشاء نوع توصية',
        nameEn: 'Create Recommendation Type',
        checked: false,
      },
      {
        id: 'UpdateRecommendationType',
        name: 'تعديل نوع توصية',
        nameAr: 'تعديل نوع توصية',
        nameEn: 'Update Recommendation Type',
        checked: false,
      },
      {
        id: 'DeleteRecommendationType',
        name: 'حذف نوع توصية',
        nameAr: 'حذف نوع توصية',
        nameEn: 'Delete Recommendation Type',
        checked: false,
      },
    ],
  },

  {
    id: 'ConsultantGroup',
    name: 'مجموعات المستشارين',
    nameAr: 'مجموعات المستشارين',
    nameEn: ' Consultant Groups',
    checked: true,
    pages: [
      {
        id: 'ViewConsultantGroup',
        name: 'عرض مجموعات المستشارين',
        nameAr: 'عرض مجموعات المستشارين',
        nameEn: 'View Consultant Groups',
        checked: false,
      },
      {
        id: 'CreateConsultantGroup',
        name: 'إنشاء مجموعة مستشارين',
        nameAr: 'إنشاء مجموعة مستشارين',
        nameEn: 'Create  Consultant Group',
        checked: false,
      },
      {
        id: 'UpdateConsultantGroup',
        name: 'تعديل مجموعة مستشارين',
        nameAr: 'تعديل مجموعة مستشارين',
        nameEn: 'Update Consultant Group',
        checked: false,
      },
      {
        id: 'DeleteConsultantGroup',
        name: 'حذف مجموعة مستشارين',
        nameAr: 'حذف مجموعة مستشارين',
        nameEn: 'Delete Consultant Group',
        checked: false,
      },
    ],
  },

  {
    id: 'ExportedAttachmentType',
    name: 'أنواع المرفقات',
    nameAr: 'أنواع المرفقات',
    nameEn: 'Exported attachment types',
    checked: true,
    pages: [
      {
        id: 'ViewExportedAttachmentType',
        name: ' عرض أنواع المرفقات',
        nameAr: ' عرض أنواع المرفقات',
        nameEn: 'View attachment types',
        checked: false,
      },
      {
        id: 'CreateExportedAttachmentType',
        name: 'إنشاء نوع مرفق',
        nameAr: 'إنشاء نوع مرفق',
        nameEn: 'Create attachment type',
        checked: false,
      },
      {
        id: 'UpdateExportedAttachmentType',
        name: ' تعديل نوع مرفق',
        nameAr: ' تعديل نوع مرفق',
        nameEn: 'Update attachment type',
        checked: false,
      },
      {
        id: 'DeleteExportedAttachmentType',
        name: ' حذف نوع مرفق',
        nameAr: ' حذف نوع مرفق',
        nameEn: 'Delete attachment type',
        checked: false,
      },
    ],
  },
  {
    id: 'OrganizationStructure',
    name: 'هيكلية الامانة',
    nameAr: 'هيكلية الامانة',
    nameEn: 'Organization Structure',
    checked: true,
    pages: [
      {
        id: 'ViewOrganizationStructure',
        name: 'عرض هيكلية الأمانة',
        nameAr: 'عرض هيكلية الأمانة',
        nameEn: 'View organization structure',
        checked: false,
      },
      {
        id: 'CreateOrganizationStructure',
        name: 'إنشاء هيكلية الأمانة',
        nameAr: 'إنشاء هيكلية الأمانة',
        nameEn: 'Create organization structure',
        checked: false,
      },
      {
        id: 'UpdateOrganizationStructure',
        name: 'تعديل هيكلية الأمانة',
        nameAr: 'تعديل هيكلية الأمانة',
        nameEn: 'Update organization structure',
        checked: false,
      },
      {
        id: 'DeleteOrganizationStructure',
        name: 'حذف  هيكلية الأمانة',
        nameAr: 'حذف  هيكلية الأمانة',
        nameEn: 'Delete organization structure',
        checked: false,
      },
    ],
  },
  {
    id: 'NewsPost',
    name: 'اخر الاخبار',
    nameAr: 'اخر الاخبار',
    nameEn: 'News posts',
    checked: true,
    pages: [
      {
        id: 'ViewNewsPost',
        name: 'عرض اخر الاخبار',
        nameAr: 'عرض اخر الاخبار',
        nameEn: 'View news posts',
        checked: false,
      },
      {
        id: 'CreateNewsPost',
        name: 'إنشاء خبر',
        nameAr: 'إنشاء خبر',
        nameEn: 'Create news post',
        checked: false,
      },
      {
        id: 'UpdateNewsPost',
        name: 'تعديل خبر',
        nameAr: 'تعديل خبر',
        nameEn: 'Update news post',
        checked: false,
      },
      {
        id: 'DeleteNewsPost',
        name: 'حذف خبر',
        nameAr: 'حذف خبر',
        nameEn: 'Delete news post',
        checked: false,
      },
    ],
  },
  {
    id: 'Settings',
    name: 'ادارة النظام',
    nameAr: 'ادارة النظام',
    nameEn: 'System settings',
    checked: true,
    pages: [
      {
        id: 'ViewSettings',
        name: 'عرض ادارة النظام',
        nameAr: 'عرض ادارة النظام',
        nameEn: 'View system settings',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
    ],
  },
  {
    id: 'CommitteeSequence',
    name: 'تسلسل أرقام المحاضر',
    nameAr: 'تسلسل أرقام المحاضر',
    nameEn: 'User permissions',
    checked: true,
    pages: [
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },

      {
        id: 'ResetCommitteeSequence',
        name: 'اعادة بدء الترقيم',
        nameAr: 'اعادة بدء الترقيم',
        nameEn: 'Restart numbering',
        checked: false,
      },
    ],
  },

  {
    id: 'IosVersion',
    name: 'صلاحيات التطبيق',
    nameAr: 'صلاحيات التطبيق',
    nameEn: 'Process type justifications',
    checked: true,
    pages: [
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: 'AddNewIosVersion',
        name: 'إضافة إصدار جديد',
        nameAr: 'إضافة إصدار جديد',
        nameEn: 'Add new IOS version',
        checked: false,
      },
      {
        id: 'IosShareFiles',
        name: 'مشاركة الملفات',
        nameAr: 'مشاركة الملفات',
        nameEn: 'IOS sharing files',
        checked: false,
      },
    ],
  },
  {
    id: 'Notifications',
    name: 'الاشعارات',
    nameAr: 'الاشعارات',
    nameEn: 'Process type justifications',
    checked: true,
    pages: [
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: 'ManageNotificationPreferences',
        name: 'طريقة الاشعار',
        nameAr: 'طريقة الاشعار',
        nameEn: "Notification's method",
        checked: false,
      },
      {
        id: 'ManageNotificationCategories',
        name: 'اشعارات التطبيق',
        nameAr: 'اشعارات التطبيق',
        nameEn: 'App Notifications',
        checked: false,
      },
    ],
  },
  {
    id: 'Priority',
    name: 'الأهمية',
    nameAr: 'الأهمية',
    nameEn: 'Priorities',
    checked: true,
    pages: [
      {
        id: 'ViewPriority',
        name: 'عرض الأهمية',
        nameAr: 'عرض الأهمية',
        nameEn: 'View priorities',
        checked: false,
      },
      {
        id: 'CreatePriority',
        name: 'إنشاء أهمية',
        nameAr: 'إنشاء أهمية',
        nameEn: 'Create priority',
        checked: false,
      },
      {
        id: 'UpdatePriority',
        name: 'تعديل أهمية',
        nameAr: 'تعديل أهمية',
        nameEn: 'Update priority',
        checked: false,
      },
      {
        id: 'DeletePriority',
        name: 'حذف أهمية',
        nameAr: 'حذف أهمية',
        nameEn: 'Delete priority',
        checked: false,
      },
    ],
  },

  {
    id: 'SignatureFormat',
    name: 'توقيعات اللجان',
    nameAr: 'توقيعات اللجان',
    nameEn: 'Signature formats',
    checked: true,
    pages: [
      {
        id: 'ViewSignatureFormat',
        name: 'عرض توقيعات اللجان',
        nameAr: 'عرض توقيعات اللجان',
        nameEn: 'View signature formats',
        checked: false,
      },
      {
        id: 'CreateSignatureFormat',
        name: 'إنشاء توقيعات اللجان',
        nameAr: 'إنشاء توقيعات اللجان',
        nameEn: 'Create signature format',
        checked: false,
      },
      {
        id: 'UpdateSignatureFormat',
        name: 'تعديل توقيعات اللجان',
        nameAr: 'تعديل توقيعات اللجان',
        nameEn: 'Update signature format',
        checked: false,
      },
      {
        id: 'DeleteSignatureFormat',
        name: 'حذف توقيعات اللجان',
        nameAr: 'حذف توقيعات اللجان',
        nameEn: 'Delete signature format',
        checked: false,
      },
    ],
  },
  {
    id: 'InitiationsSettings',
    name: 'اعدادات التراكين',
    nameAr: 'اعدادات التراكين',
    nameEn: 'Initiations settings',
    checked: true,
    pages: [
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },

      {
        id: 'HasInitiation',
        name: 'إنشاء تركين',
        nameAr: 'إنشاء تركين',
        nameEn: 'Create initiation',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: 'UserInitiationManagement',
        name: 'ادارة التركينات',
        nameAr: 'ادارة التركينات',
        nameEn: 'Initiations management',
        checked: false,
      },
    ],
  },
  {
    id: 'SignaturesSettings',
    name: 'اعدادات التواقيع',
    nameAr: 'اعدادات التواقيع',
    nameEn: 'Signatures settings',
    checked: true,
    pages: [
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },

      {
        id: 'HasSignature',
        name: 'إنشاء توقيع',
        nameAr: 'إنشاء توقيع',
        nameEn: 'Create signature',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: 'UserSignatureManagement',
        name: 'ادارة التوقيعات',
        nameAr: 'ادارة التوقيعات',
        nameEn: 'Signatures management',
        checked: false,
      },
    ],
  },
  /* {
    id: 'DocumentsLibrary',
    name: 'الملفات والمستندات',
    nameAr: 'الملفات والمستندات',
    nameEn: 'Documents',
    checked: true,
    pages: [
      {
        id: 'ViewDocumentsLibrary',
        name: 'عرض الملفات والمستندات',
        nameAr: 'عرض الملفات والمستندات',
        nameEn: 'View documents',
        checked: false,
      },
      {
        id: 'DocumentsLibraryCreateFolder',
        name: 'إنشاء مجلد',
        nameAr: 'إنشاء مجلد',
        nameEn: 'Create folder',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: 'DocumentsLibraryUploadFile',
        name: 'رفع ملف',
        nameAr: 'رفع ملف',
        nameEn: 'Upload file',
        checked: false,
      },
      {
        id: 'SynchronizationDocumentsLibrary',
        name: 'مزامنة الملفات والمستندات',
        nameAr: 'مزامنة الملفات والمستندات',
        nameEn: 'Syncronize documents',
        checked: false,
      },
    ],
  }, */
];

export const userPermissionsTree: Permission[] = [
  {
    id: 'User',
    name: 'المستخدمين',
    nameAr: 'المستخدمين',
    nameEn: 'Users',
    checked: true,
    pages: [
      {
        id: 'ViewUser',
        name: 'عرض المستخدمين',
        nameAr: 'عرض المستخدمين',
        nameEn: 'View users',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: 'SynchronizationUsers',
        name: 'مزامنة المستخدمين',
        nameAr: 'مزامنة المستخدمين',
        nameEn: 'Syncronize users',
        checked: false,
      },
      {
        id: 'BiosStarUsersAsync',
        name: 'مزامنة الحضور والانصراف',
        nameAr: 'مزامنة الحضور والانصراف',
        nameEn: 'Syncronize time attendance',
        checked: false,
      },
      {
        id: 'ModifyUserPermissions',
        name: 'تعديل صلاحيات المستخدمين',
        nameAr: 'تعديل صلاحيات المستخدمين',
        nameEn: 'Modify user permissions',
        checked: false,
      },
    ],
  },

  {
    id: 'Role',
    name: 'الأدوار',
    nameAr: 'الأدوار',
    nameEn: 'RoleS',
    checked: true,
    pages: [
      {
        id: 'ViewRole',
        name: 'عرض الأدوار',
        nameAr: 'عرض الأدوار',
        nameEn: 'View roles',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: '',
        name: '',
        nameAr: '',
        nameEn: '',
        checked: false,
      },
      {
        id: 'ModifyRolePermissions',
        name: 'تعديل صلاحيات الأدوار',
        nameAr: 'تعديل صلاحيات الأدوار',
        nameEn: 'modify role permissions',
        checked: false,
      },
      {
        id: 'SynchronizationRoles',
        name: 'مزامنة الأدوار',
        nameAr: 'مزامنة الأدوار',
        nameEn: 'Syncronize roles',
        checked: false,
      },
    ],
  },
];

export const PermissionsObj = {
  Escalation: 'Escalation',
  ViewFoundations: 'ViewFoundation',
  CreateFoundation: 'CreateFoundation',
  UpdateFoundation: 'UpdateFoundation',
  DeleteFoundation: 'DeleteFoundation',
  ViewSectors: 'ViewSector',
  CreateSector: 'CreateSector',
  UpdateSector: 'UpdateSector',
  DeleteSector: 'DeleteSector',

  ViewExportedAttachmentType: 'ViewExportedAttachmentType',
  CreateExportedAttachmentType: 'ViewExportedAttachmentType',
  UpdateExportedAttachmentType: 'UpdateExportedAttachmentType',
  DeleteExportedAttachmentType: 'DeleteExportedAttachmentType',

  ViewClassifications: 'ViewClassifications',
  CreateClassification: 'CreateClassification',
  UpdateClassification: 'UpdateClassification',
  DeleteClassification: 'DeleteClassification',
  ViewBenefitTypes: 'ViewBenefitType',
  CreateBenefitType: 'CreateBenefitType',
  UpdateBenefitType: 'UpdateBenefitType',
  DeleteBenefitType: 'DeleteBenefitType',
  ViewUiForms: 'ViewUiForm',
  CreateUiForm: 'CreateUiForm',
  UpdateUiForm: 'UpdateUiForm',
  DeleteUiForm: 'DeleteUiForm',
  ViewRequestTypes: 'ViewRequestType',
  CreateRequestType: 'CreateRequestType',
  UpdateRequestType: 'UpdateRequestType',
  DeleteRequestType: 'DeleteRequestType',
  ViewPriorities: 'ViewPriority',
  CreatePriority: 'CreatePriority',
  UpdatePriority: 'UpdatePriority',
  DeletePriority: 'DeletePriority',
  ViewOutcomes: 'ViewOutcome',
  CreateOutcome: 'CreateOutcome',
  UpdateOutcome: 'UpdateOutcome',
  DeleteOutcome: 'DeleteOutcome',
  ViewRecommendationTypes: 'ViewRecommendationType',
  CreateRecommendationType: 'CreateRecommendationType',
  UpdateRecommendationType: 'UpdateRecommendationType',
  DeleteRecommendationType: 'DeleteRecommendationType',
  ViewReferralJustifications: 'ViewReferralJustification',
  CreateReferralJustification: 'CreateReferralJustification',
  UpdateReferralJustification: 'UpdateReferralJustification',
  DeleteReferralJustification: 'DeleteReferralJustification',
  ViewRequestContainers: 'ViewRequestContainer',
  CreateRequestContainer: 'CreateRequestContainer',
  UpdateRequestContainer: 'UpdateRequestContainer',
  DeleteRequestContainer: 'DeleteRequestContainer',
  ModifyProcessType: 'ModifyProcessType',
  ViewPendingRequests: 'ViewPendingRequests',
  //AmountsManipulation: 'AmountsManipulation',
  ViewRequests: 'ViewRequest',
  CreateRequest: 'CreateRequest',
  UpdateRequest: 'UpdateRequest',
  DeleteRequest: 'DeleteRequest',
  ResetRequestWorkflowSteps: 'ResetRequestWorkflowSteps',
  ExportRequestsToExcel: 'ExportRequestsToExcel',

  //RequestPriorityManipulation: 'RequestPriorityManipulation',
  //RequestProcessTypeManipulation: 'RequestProcessTypeManipulation',

  //RequestEscalationDurationManipulation:
  //  'RequestEscalationDurationManipulation',
  // RequestAmountsManipulation: 'RequestAmountsManipulation',
  //ModifyingDeliveryDate: 'ModifyingDeliveryDate',
  //SetRequestEscalation: 'SetRequestEscalation',
  /* ViewRequestExtension: 'ViewRequestExtension',
  CreateRequestExtension: 'CreateRequestExtension',
  RequestExtensionApproval: 'RequestExtensionApproval', */
  ViewActions: 'ViewAction',
  CreateAction: 'CreateAction',
  UpdateAction: 'UpdateAction',
  DeleteAction: 'DeleteAction',
  ViewStepCategories: 'ViewStepCategory',
  CreateStepCategory: 'CreateStepCategory',
  UpdateStepCategory: 'UpdateStepCategory',
  DeleteStepCategory: 'DeleteStepCategory',
  ViewSteps: 'ViewStep',
  CreateStep: 'CreateStep',
  UpdateStep: 'UpdateStep',
  DeleteStep: 'DeleteStep',
  ViewActors: 'ViewActor',
  CreateActor: 'CreateActor',
  UpdateActor: 'UpdateActor',
  DeleteActor: 'DeleteActor',
  ViewSchemas: 'ViewSchema',
  CreateSchemas: 'CreateSchema',
  UpdateSchema: 'UpdateSchema',
  DeleteSchema: 'DeleteSchema',

  CreateInquiry: 'CreateInquiry',
  ViewInquiry: 'ViewInquiry',
  ReplyInquiry: 'ReplyInquiry',
  ReplyApprovalInquiry: 'ReplyApprovalInquiry',

  ViewOrganizationsStructure: 'ViewOrganizationStructure',
  CreateOrganizationStructure: 'CreateOrganizationStructure',
  UpdateOrganizationStructure: 'UpdateOrganizationStructure',
  DeleteOrganizationStructure: 'DeleteOrganizationStructure',

  UserDelegate: 'UserDelegate',
  ViewUsersDelegations: 'ViewUsersDelegations',
  AdministrateDelegations: 'AdministrateDelegations',

  ViewNewsPost: 'ViewNewsPost',
  CreateNewsPost: 'CreateNewsPost',
  UpdateNewsPost: 'UpdateNewsPost',
  DeleteNewsPost: 'DeleteNewsPost',

  ViewMeetings: 'ViewMeeting',
  CreateMeeting: 'CreateMeeting',
  UpdateMeeting: 'UpdateMeeting',
  ConfirmMeetingAttendance: 'ConfirmMeetingAttendance',
  DeleteMeeting: 'DeleteMeeting',
  MeetingAddUnScheduledRequests: 'MeetingAddUnScheduledRequests',

  ViewSignatureFormats: 'ViewSignatureFormat', //توقيعات اللجان
  CreateSignatureFormat: 'CreateSignatureFormat',
  UpdateSignatureFormat: 'UpdateSignatureFormat',
  DeleteSignatureFormat: 'DeleteSignatureFormat',

  ViewUsers: 'ViewUser',
  SynchronizationUsers: 'SynchronizationUsers',
  BiosStarUsersAsync: 'BiosStarUsersAsync',

  ViewRoles: 'ViewRole',
  ModifyRolePermissions: 'ModifyRolePermissions',
  SynchronizationRoles: 'SynchronizationRoles',

  ModifyWorkflow: 'ModifyWorkflowDesigns', //ال engine

  ViewRecords: 'ViewRecord',
  RemoveRecordMemberAction: 'RemoveRecordMemberAction',
  RecordPhoneApprovalAction: 'RecordPhoneApprovalAction',

  ReplyRecordConservatism: 'ReplyRecordConservatism',
  UpdateRecordSignatureFormat: 'UpdateRecordSignatureFormat',

  ViewNotes: 'ViewNote',

  ViewRegularReports: 'ViewRegularReports',
  CreateRegularReports: 'CreateRegularReports',
  SynchronizationRegularReports: 'SynchronizationRegularReports',
  ViewReportsLogs: 'ViewReportsLogs',
  /*   ViewDocumentsLibrary: 'ViewDocumentsLibrary',
  DocumentsLibraryCreateFolder: 'DocumentsLibraryCreateFolder', //Doesn't have a view yet
  DocumentsLibraryUploadFile: 'DocumentsLibraryUploadFile', //Doesn't have a view yet
  SynchronizationDocumentsLibrary: 'SynchronizationDocumentsLibrary',
 */
  ViewSettings: 'ViewSettings', //ادارة النظام

  ModifyUserPermissions: 'ModifyUserPermissions',

  ResetCommitteeSequence: 'ResetCommitteeSequence',

  ///مجموعات المستشارين
  ViewConsultantGroups: 'ViewConsultantGroup',
  CreateConsultantGroup: 'CreateConsultantGroup',
  UpdateConsultantGroup: 'UpdateConsultantGroup',
  DeleteConsultantGroup: 'DeleteConsultantGroup',

  ///مبررات الية المعالجة

  ViewProcessTypeJustifications: 'ViewProcessTypeJustification',
  CreateProcessTypeJustification: 'CreateProcessTypeJustification',
  UpdateProcessTypeJustification: 'UpdateProcessTypeJustification',
  DeleteProcessTypeJustification: 'DeleteProcessTypeJustification',

  UpdateRequestContainerAccessibility: 'UpdateRequestContainerAccessibility',
  CommitteePhoneApprovals: 'CommitteePhoneApprovals',
  ///////قائمة الوثائق
  ViewDocumentTypes: 'ViewDocumentType',
  CreateDocumentType: 'CreateDocumentType',
  UpdateDocumentType: 'UpdateDocumentType',
  DeleteDocumentType: 'DeleteDocumentType',

  //صلاحيات التطبيق
  AddNewIosVersion: 'AddNewIosVersion',
  IosShareFiles: 'IosShareFiles',

  //الاشعارات
  ManageNotificationPreferences: 'ManageNotificationPreferences',
  ManageNotificationCategories: 'ManageNotificationCategories',

  HasInitiation: 'HasInitiation',
  UserSignatureManagement: 'UserSignatureManagement',

  //بيانات التسليم
  ViewDeliveryReceipt: 'ViewDeliveryReceipt',
  CreateDeliveryReceipt: 'CreateDeliveryReceipt',
  UpdateDeliveryReceipt: 'UpdateDeliveryReceipt',

  ViewRegulatoryDocuments: 'ViewRegulatoryDocuments',
  CreateRegulatoryDocuments: 'CreateRegulatoryDocuments',
  UpdateRegulatoryDocuments: 'UpdateRegulatoryDocuments',
  DeleteRegulatoryDocuments: 'DeleteRegulatoryDocuments',
};
