export enum Actions {
  VIEW = 'view',
  COPY = 'copy',
  EDIT = 'edit',
  DELETE = 'delete',
  DELETEPENDING = 'deletePendingContract',
  CHART = 'chart',
  APPROVE = 'approve',
  REJECT = 'reject',
  DETAILS = 'Details',
  START = 'Start',
  PREPARE = 'Prepare',
  CUSTOMACTION = 'customAction',
  CUSTOMACTIONMANAGE = 'customActionManage',
  CUSTOMACTIONEXTEND = 'customActionExtend',
  CUSTOMACTIONDETAILS = 'customActionDetails',
  STATUS = 'status',
  ALLOCATE = 'allocate',
  CUSTOMHOVER = 'customhover',
  ACCESSIBILITY = 'accessibility',
  ADDATTACHMENT = 'addAttachment',
  OPENLINK = 'openLink',
}
