export enum TransactionActionType {
  Start = 1,
  Approve = 2,
  Assignment = 3,
  Delegate = 4,
  ChangeRequest = 5,
  RedirectingRequest = 6,
  ExportToRC = 7,
  ExportToEE = 8,
  Signature = 9,
  Initiate = 10,
  Escalation = 11,
  Conservatism = 12,
  SelectConsultants = 13,
  Recommendation = 14,
  Noting = 15,
  PhoneApproval = 16,
  SelectProcessType = 17,
  AddActorToClassifiedRequests = 18,
  Archiving = 19,
  Close = 20,
}
